INSERT INTO Eventtable (ID, Name, Details, Image)
VALUES
('1', 'Go to the Park', 'Pick a local park to take a small walk, watch grandchildren play, etc.', ""),
('2', 'Play a Boardgame', 'Play chess, checkers, dominoes, or try a new game', ''),
('3', 'Bake Something', "Bake cookies, a cake, or grandma's specialty item", ''),
('4', 'Make a Family Tree', 'Take some time to learn about your family history', ''),
('5', 'Take Turns Reading a Book', 'Introduce your favorite book to your grandparent or find out what their favorite is', ''),
('6', 'Watch a Movie', 'Watch the latest blockbuster or a timeless classic', ''),
('7', 'Sing Karaoke', 'Whether you are a talented singer or not, karaoke can be fun for everyone! Find a local karaoke place or find an app on your phone.', ''),
('8', 'Paint a Picture', 'Visit a painting studio or just pick a simple painting online to recreate together'),
('9', 'Go On a Picnic', 'Picnics are fun for the whole family. Make some simple sandwiches or pick up fried chicken on the way', ''),
('10', 'Look At Old Family Photos', 'Let your parents/grandparents share memories inspired by old photos. Take the time to write some details on the back to remember for later.', ''),
('11', 'Work on a Jigsaw Puzzle', 'This can be something you come back to from visit to visit.', ''),
('12', 'Work In the Garden', 'Plant some flowers, pull weeds, or simply repot a plant', ''),
('13', 'Make Jewelry', 'Pick up some supplies from a local craft store to make friendship bracelets, matching necklaces, or some fancy rings', ''),
('14', 'Play Video Games', 'People of all ages love video games', ''),
('15', 'Complete a Crossword or Sudoku Puzzle', 'Use your combined knowledge to complete your favorite puzzle', ''),
('16', 'Play Card Games', '', ''),
('17', 'Visit a Mueseum', "It could be local art mueseum, children's mueseum", ''),
('18', 'Visit a Brewery', 'Does your family like beer? Checkout some local brews together', '')
